apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gadget.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    # update is needed by traceloop gadget.
    verbs: ["update"]
