// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package sockhash

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sockhashGadgetTcpStreamConn struct {
	_       structs.HostLayout
	Version uint8
	Pad     [3]uint8
	Sport   uint16
	Dport   uint16
	SaddrV4 uint32
	_       [12]byte
	DaddrV4 uint32
	_       [12]byte
	Proc    struct {
		_       structs.HostLayout
		Comm    [16]int8
		Pid     uint32
		Tid     uint32
		MntnsId uint64
		Creds   struct {
			_   structs.HostLayout
			Uid uint32
			Gid uint32
		}
		Parent struct {
			_    structs.HostLayout
			Comm [16]int8
			Pid  uint32
			Tid  uint32
		}
	}
}

type sockhashGadgetTcpStreamTuple struct {
	_       structs.HostLayout
	Version uint8
	Pad     [3]uint8
	Sport   uint16
	Dport   uint16
	Saddr   [16]uint8
	Daddr   [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	sockhashMapGadgetSockhash          = "gadget_sockhash"
	sockhashMapGadgetTcpStreamConns    = "gadget_tcp_stream_conns"
	sockhashMapGadgetTcpStreamPorts    = "gadget_tcp_stream_ports"
	sockhashMapGadgetTcpStreamTuples   = "gadget_tcp_stream_tuples"
	sockhashProgGadgetTcpStreamConnect = "gadget_tcp_stream_connect"
	sockhashProgGadgetTcpStreamSockops = "gadget_tcp_stream_sockops"
)

// loadSockhash returns the embedded CollectionSpec for sockhash.
func loadSockhash() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockhashBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sockhash: %w", err)
	}

	return spec, err
}

// loadSockhashObjects loads sockhash and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sockhashObjects
//	*sockhashPrograms
//	*sockhashMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSockhashObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSockhash()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sockhashSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockhashSpecs struct {
	sockhashProgramSpecs
	sockhashMapSpecs
	sockhashVariableSpecs
}

// sockhashProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockhashProgramSpecs struct {
	GadgetTcpStreamConnect *ebpf.ProgramSpec `ebpf:"gadget_tcp_stream_connect"`
	GadgetTcpStreamSockops *ebpf.ProgramSpec `ebpf:"gadget_tcp_stream_sockops"`
}

// sockhashMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockhashMapSpecs struct {
	GadgetSockhash        *ebpf.MapSpec `ebpf:"gadget_sockhash"`
	GadgetTcpStreamConns  *ebpf.MapSpec `ebpf:"gadget_tcp_stream_conns"`
	GadgetTcpStreamPorts  *ebpf.MapSpec `ebpf:"gadget_tcp_stream_ports"`
	GadgetTcpStreamTuples *ebpf.MapSpec `ebpf:"gadget_tcp_stream_tuples"`
}

// sockhashVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockhashVariableSpecs struct {
}

// sockhashObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSockhashObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockhashObjects struct {
	sockhashPrograms
	sockhashMaps
	sockhashVariables
}

func (o *sockhashObjects) Close() error {
	return _SockhashClose(
		&o.sockhashPrograms,
		&o.sockhashMaps,
	)
}

// sockhashMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSockhashObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockhashMaps struct {
	GadgetSockhash        *ebpf.Map `ebpf:"gadget_sockhash"`
	GadgetTcpStreamConns  *ebpf.Map `ebpf:"gadget_tcp_stream_conns"`
	GadgetTcpStreamPorts  *ebpf.Map `ebpf:"gadget_tcp_stream_ports"`
	GadgetTcpStreamTuples *ebpf.Map `ebpf:"gadget_tcp_stream_tuples"`
}

func (m *sockhashMaps) Close() error {
	return _SockhashClose(
		m.GadgetSockhash,
		m.GadgetTcpStreamConns,
		m.GadgetTcpStreamPorts,
		m.GadgetTcpStreamTuples,
	)
}

// sockhashVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSockhashObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockhashVariables struct {
}

// sockhashPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSockhashObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockhashPrograms struct {
	GadgetTcpStreamConnect *ebpf.Program `ebpf:"gadget_tcp_stream_connect"`
	GadgetTcpStreamSockops *ebpf.Program `ebpf:"gadget_tcp_stream_sockops"`
}

func (p *sockhashPrograms) Close() error {
	return _SockhashClose(
		p.GadgetTcpStreamConnect,
		p.GadgetTcpStreamSockops,
	)
}

func _SockhashClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockhash_x86_bpfel.o
var _SockhashBytes []byte
